from pydantic import BaseModel, Field
from typing import Optional


class JDState(BaseModel):
    """State that flows through the job description generation pipeline."""
    
    # User's original input
    user_input: str = Field(
        default="",
        description="All job details provided by the user"
    )
    
    # Generated by validation_node
    validation_result: Optional[str] = Field(
        default=None,
        description="Validation result: 'valid' or error message"
    )
    
    normalized_input: Optional[str] = Field(
        default=None,
        description="Normalized and structured user input"
    )
    
    # Generated by draft_node
    draft: Optional[str] = Field(
        default=None,
        description="Draft version of the job description"
    )
    
    # Generated by quality_check_node
    quality_check: Optional[str] = Field(
        default=None,
        description="JSON result with quality score and issues"
    )
    
    # Updated by rewrite_node
    rewrite_attempts: int = Field(
        default=0,
        description="Number of times draft was rewritten (max 3)"
    )
    
    # Generated by review_node
    reviewed: Optional[str] = Field(
        default=None,
        description="Reviewed and ATS-optimized version"
    )
    
    # Generated by final_output_node
    final_markdown: Optional[str] = Field(
        default=None,
        description="Final JD in markdown format"
    )
    
    final_json: Optional[str] = Field(
        default=None,
        description="Final JD in JSON format"
    )
    
    final_text: Optional[str] = Field(
        default=None,
        description="Final JD in plain text format"
    )